routes/web.php
<?php
use App\Http\Controllers\FrontendController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontendController@index')->name('frontend.index');
Route::get('blogs/{dkc}', 'FrontendController@show')->name('frontend.show');
Route::get('blogs/categories/{category}', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('blogs/users/{user}', [FrontendController::class, 'user'])->name('frontend.user');

Route::get('mails/send', 'MailController@send')->name('mail.send');

Auth::routes();

Route::middleware(['auth'])->group(function(){

  Route::get('home', 'DkcController@index')->name('home');

  Route::resource('categories', 'CategoryController');

  Route::resource('tags', 'TagController');

  Route::resource('dkcs', 'DkcController');

  Route::resource('posts', 'PostController');

  Route::get('trashed-posts', 'PostController@trashed')->name('posts.trashed');

  Route::get('restore-post/{id}', 'PostController@restore')->name('posts.restore');



  Route::post('/upload/file', 'DkcController@upload')->name('dkcs.upload');

  Route::resource('activities', 'ActivityController');

  Route::resource('donates', 'DonateController');

});

Route::middleware(['auth', 'admin'])->group(function(){

  Route::resource('users', 'UserController');
  Route::post('users/make-admin/{user}', 'UserController@makeAdmin')->name('users.make-admin');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
  protected $guarded = [];


  public function activities()
  {
    return $this->hasMany(Activity::class);
  }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Requests\Categories\CategoriesRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('blog.category.index')->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('blog.category.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoriesRequest $request)
    {
      Category::create($request->validated());  
      return redirect(route('categories.index'))->with('status', 'Category Create Successful!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
      return view('blog.category.form')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoriesRequest $request, Category $category)
    {
      $category->update($request->validated());

      return redirect(route('categories.index'))->with('status', 'Update Successful!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
      if($category->posts->count()>0){
        return redirect(route('categories.index'))->with('error', 'Cannot be deleted because it has some post.');
      }

      $category->delete();
      return redirect(route('categories.index'))->with('status', 'Deleted Successful!');
    }
}

resources/views/blog/category/form.blade.php
@extends('layouts.main')

@section('error')
  @if($errors->any())
    @foreach($errors->all() AS $error)  
      <div class="alert alert-danger">{{$error}}</div>
    @endforeach
  @endif
@endsection

@section('content')
  <div class="card">
    <div class="card-body">
      <form action="{{isset($category)?route('categories.update', $category->id):route('categories.store')}}" method="post">
        @csrf
        @if(isset($category))
          @method('PUT')
        @endif
        <div class="form-group">
          <label for="name">{{isset($category)?'Edit':'Create'}} Category</label>
          <input type="text" name="name" id="name" class="form-control" value="{{isset($category)?$category->name:''}}">
        </div>
        <button class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
@endsection

@section('scripts')
  <script>
    document.getElementById('name').focus()
  </script>
@endsection

resources/views/blog/category/index.blade.php
@extends('layouts.main')

@section('title', 'Categories')

@section('error')
  @if(session('error'))
    <div class="alert alert-danger">{{session('error')}}</div>
  @endif
@endsection

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header d-flex">
      <div class="mr-auto">Categories</div>
      <a href="{{route('categories.create')}}" class="btn btn-secondary">Add</a>
    </h4>
    <div class="card-body">

      <table class="table mt-2">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Count</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($categories AS $category)
          <tr>
            <td>{{$category->id}}</td>
            <td>{{$category->name}}</td>
            <td>{{$category->activities->count()}}</td>
            <td>
              <a href="{{route('categories.edit', $category->id)}}" class="btn  btn-outline-info">Edit</a>
              <form action="{{route('categories.destroy', $category->id)}}" method="post" class="d-inline-block ml-2">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-outline-danger">Delete</button>
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection