routes/web.php
<?php
use App\Http\Controllers\FrontendController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontendController@index')->name('frontend.index');
Route::get('blogs/{dkc}', 'FrontendController@show')->name('frontend.show');
Route::get('blogs/categories/{category}', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('blogs/users/{user}', [FrontendController::class, 'user'])->name('frontend.user');

Route::get('mails/send', 'MailController@send')->name('mail.send');

Auth::routes();

Route::middleware(['auth'])->group(function(){

  Route::get('home', 'DkcController@index')->name('home');

  Route::resource('categories', 'CategoryController');

  Route::resource('tags', 'TagController');

  Route::resource('dkcs', 'DkcController');

  Route::resource('posts', 'PostController');

  Route::get('trashed-posts', 'PostController@trashed')->name('posts.trashed');

  Route::get('restore-post/{id}', 'PostController@restore')->name('posts.restore');



  Route::post('/upload/file', 'DkcController@upload')->name('dkcs.upload');

  Route::resource('activities', 'ActivityController');

  Route::resource('donates', 'DonateController');

});

Route::middleware(['auth', 'admin'])->group(function(){

  Route::resource('users', 'UserController');
  Route::post('users/make-admin/{user}', 'UserController@makeAdmin')->name('users.make-admin');

});

app/Activity.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
	protected $fillable = ['title', 'description', 'category_id', 'start_at', 'end_at', 'user_id', 'cover_img'];

	protected $dates = [
		'start_at',
		'end_at',
	];

	public function category()
	{
		return $this->belongsTo(Category::class);
	}

	public function getCoverImgAttribute($value)
	{
		return 'storage/'.$value;
	}
}

app/Http/Controllers/ActivityController.php
<?php

namespace App\Http\Controllers;

use App\Activity;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Requests\Activities\FormActivityRequest;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ActivityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('activity.index')
            ->withActivities(Activity::paginate(5));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('activity.form')->withCategories(Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FormActivityRequest $request)
    {
			$attribute = $request->all();
			$attribute['category_id'] = 1;
			$attribute['user_id'] = auth()->user()->id;
			if($request->hasFile('cover_img')){
				$attribute['cover_img'] = $request->cover_img->store('public/activities');
			}
			$activity = Activity::create($attribute);
			return redirect(route('activities.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function show(Activity $activity)
    {
      return view('activity.view')->withActivity($activity);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function edit(Activity $activity)
    {
			return view('activity.form')
				->withActivity($activity)
				->withCategories(Category::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function update(FormActivityRequest $request, Activity $activity)
    {
      $attribute = $request->all();
			$attribute['category_id'] = 1;
			$attribute['user_id'] = auth()->user()->id;
			if($request->hasFile('cover_img')){
				if($activity->getOriginal('cover_img')){
					Storage::delete($activity->getOriginal('cover_img'));
				}
				$attribute['cover_img'] = $request->cover_img->store('public/activities');
			}
			$activity->update($attribute);
			
			// $image = Image::make(public_path($activity->cover_img))->fit(500, 500, null, 'top');
			// $image->save();

			return redirect(route('activities.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Activity  $activity
     * @return \Illuminate\Http\Response
     */
    public function destroy(Activity $activity)
    {
			Storage::delete($activity->cover_img);
			$activity->delete();
			return redirect(route('activities.index'));
    }
}

resources/views/activity/form.blade.php
@extends('layouts.main')

@section('title', 'แบบฟอร์มกิจกรรม')

@section('error')
	@if($errors->any())
		@foreach($errors->all() AS $error)
			<div class="alert alert-danger">{{$error}}</div>
		@endforeach
	@endif
@endsection

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
	<div class="card">
		<h4 class="card-header">แบบฟอร์มกิจกรรม</h4>
		<div class="card-body">
			<form action="{{!isset($activity)? route('activities.store') : route('activities.update', $activity->id)}}" method="post" enctype="multipart/form-data">
				@csrf
				@if(isset($activity))
					@method('put')
				@endif
				<div class="form-group">
					<label for="title">ชื่อกิจกรรม</label>
					<input type="text" name="title" id="title" class="form-control" value="{{old('title', isset($activity)?$activity->title:'')}}">
				</div>
				<div class="form-group">
					<label for="description">รายละเอียด</label>
					<input type="text" name="description" id="description" class="form-control" value="{{old('description', isset($activity)?$activity->description:'')}}">
				</div>
				<div class="form-group">
					<label for="category_id">หมวดหมู่</label>
					<select name="category_id" id="category_id" class="form-control" >
						<option value="">เลือก</option>
						@foreach($categories AS $category)
							<option value="{{$category->id}}"
								@if($category->id==isset($activity)?$activity->category_id:'')
									selected
								@endif
							>{{$category->name}}</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<label for="start_at">วันเวลาเริ่ม</label>
					<input type="text" name="start_at" id="start_at" class="form-control" value="{{old('start_at', isset($activity)?$activity->start_at:'')}}">
				</div>
				<div class="form-group">
					<label for="end_at">วันเวลาสิ้นสุด</label>
					<input type="text" name="end_at" id="end_at" class="form-control" value="{{old('end_at', isset($activity)?$activity->end_at:'')}}">
				</div>
				<div class="form-group">
					<label for="cover_img">ภาพประกอบ</label>
					@if(isset($activity) && $activity->getOriginal('cover_img'))
						<img src="{{isset($activity)?asset($activity->cover_img):''}}" class="w-100">
					@endif
					<div>
						<input type="file" name="cover_img" id="cover_img" class="" value="{{old('cover_img')}}">
					</div>
				</div>
				<button type="submit" class="btn btn-primary">Save</button>
			</form>
		</div>
	</div>
@endsection

@section('scripts')
<script>

	$("#cover_img").fileinput({
		theme: "fas",
		showUpload:false,
		showCaption:false,
		showCancel:false,
		hideThumbnailContent:false,
		fileActionSettings: {
			// showZoom:false,
		},
	});

	flatpickr("#start_at", {
		enableTime: true,
		enableSeconds: true
	});

	flatpickr("#end_at", {
		enableTime: true,
		enableSeconds: true
	});

</script>
@endsection

resources/views/activity/index.blade.php
@extends('layouts.main')

@section('title', 'กิจกรรม')

@section('error')
  @if(session('error'))
    <div class="alert alert-danger">{{session('error')}}</div>
  @endif
@endsection

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
	<div class="card">
		<div class="card-header d-flex">
			<div class="mr-auto">
					<h4>กิจกรรม</h4>
			</div>
			<a href="{{route('activities.create')}}" class="btn btn-primary"><i class="fa fa-plus mr-1"></i> เพิ่มใหม่</a>
		</div>
		<div class="card-body">
			@if($activities->count())
				<table class="table">
					<thead>
						<tr>
							<th>#</th>
							<th>กิจกรรม</th>
							<th>หมวด</th>
							<th>เริ่ม</th>
							<th>สิ้นสุด</th>
							<th>รูปภาพ</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($activities AS $activity)
						<tr>
							<td>{{$activity->id}}</td>
							<td>{{$activity->title}}</td>
							<td>{{$activity->category->name}}</td>
							<td>{{$activity->start_at}}</td>
							<td>{{$activity->end_at}}</td>
							<td><img src="{{asset($activity->cover_img)}}" class="" width="100"></td>
							<td>
								<form action="{{route('activities.destroy', $activity->id)}}" method="post" class="d-inline-block ml-2 form-delete" >
									<div class="btn-group" role="group">

										<a href="{{route('activities.show', $activity->id)}}" class="btn  btn-outline-primary btn-sm">ดู</a>
										<a href="{{route('activities.edit', $activity->id)}}" class="btn  btn-outline-secondary btn-sm">แก้ไข</a>
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-outline-danger btn-form-delete btn-sm">ลบ</button>
									</div>
								</form>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			@else
				<h4 class="text-center">ไม่มีข้อมูล</h4>
			@endif
		</div>
	</div>
@endsection

resources/views/activity/view.blade.php
@extends('layouts.main')

@section('content')
  <div class="card">
    @if(asset($activity->cover_img))
      <img class="card-img-top" src="{{asset($activity->cover_img)}}" >
    @endif
    <div class="card-body">
      <h1>{{$activity->title}}</h1>
      <p class="mb-0"><a class="text-dark" href="{{route('frontend.show', $activity)}}">{{$activity->start_at->locale('th')->isoFormat('dd D MMM YYYY')}}</a></p>
      <p class="mb-0"><a class="text-dark" href="{{route('frontend.show', $activity)}}">{{$activity->end_at->locale('th')->isoFormat('dd D MMM YYYY')}}</a></p>
      <hr>
      <p>{{$activity->detail}}</p>
      <div class="mt-3"><a href="{{route('activities.index')}}" class="btn btn-primary">Back</a></div>
    </div>
  </div>
@endsection